import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache all assets generated by build process
precacheAndRoute((self as unknown as { __WB_MANIFEST: any }).__WB_MANIFEST);

// Cache images with a Cache First strategy
registerRoute(
    ({ request }) => request.destination === 'image',
    new CacheFirst({
        cacheName: 'images',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 50,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
            }),
        ],
    })
);

// Cache CSS and JavaScript files with a Stale While Revalidate strategy
registerRoute(
    ({ request }) => request.destination === 'script' || request.destination === 'style',
    new StaleWhileRevalidate({
        cacheName: 'static-resources',
    })
);

// Only cache Supabase REST (database) requests, NEVER Auth requests
registerRoute(
    ({ url }) => url.hostname.includes('supabase.co') && !url.pathname.startsWith('/auth/v1/'),
    new NetworkFirst({
        cacheName: 'supabase-api',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 100,
                maxAgeSeconds: 24 * 60 * 60, // 24 Hours
            }),
        ],
    })
);
