/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute, setCatchHandler } from 'workbox-routing';
import { NetworkFirst, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
declare const self: ServiceWorkerGlobalScope & typeof globalThis;

// Disable verbose Workbox logs in development
// @ts-ignore: This is a global flag for Workbox
self.__WB_DISABLE_DEV_LOGS = true;

// Cleanup old versions
cleanupOutdatedCaches();

// Precache all assets generated by build process
precacheAndRoute(self.__WB_MANIFEST);

// 1. FORCE UPDATE LOGIC (skipWaiting)
self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', (event) => event.waitUntil(self.clients.claim()));

self.addEventListener('message', (event: ExtendableMessageEvent) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});

// 2. CACHING STRATEGIES
const CACHE_NAME_PREFIX = 'gg-v3';

// Cache Images (CacheFirst)
registerRoute(
    ({ request }) => request.destination === 'image',
    new CacheFirst({
        cacheName: `${CACHE_NAME_PREFIX}-images`,
        plugins: [
            new ExpirationPlugin({
                maxEntries: 60,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
            }),
        ],
    })
);

// Cache Assets: Scripts, Styles, Fonts (StaleWhileRevalidate)
registerRoute(
    ({ request }) => 
        request.destination === 'script' || 
        request.destination === 'style' || 
        request.destination === 'font',
    new NetworkFirst({
        cacheName: `${CACHE_NAME_PREFIX}-assets`,
    })
);

// Cache Supabase API (NetworkFirst)
registerRoute(
    ({ url }) => url.hostname.includes('supabase.co') && !url.pathname.startsWith('/auth/v1/'),
    new NetworkFirst({
        cacheName: `${CACHE_NAME_PREFIX}-api-data`,
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            new ExpirationPlugin({
                maxEntries: 100,
                maxAgeSeconds: 12 * 60 * 60, // 12 Hours
            }),
        ],
    })
);

// 3. OFFLINE FALLBACK
const FALLBACK_HTML_URL = '/index.html';
const navigationRoute = new NavigationRoute(
    new NetworkFirst({
        cacheName: `${CACHE_NAME_PREFIX}-navigation`,
    })
);

registerRoute(navigationRoute);

setCatchHandler(async ({ event }) => {
    if (event instanceof FetchEvent && event.request.destination === 'document') {
        return (await caches.match(FALLBACK_HTML_URL)) || Response.error();
    }
    return Response.error();
});
